version: "2"
services:
  
  avalon-nginx:
    build: ./docker/images/webserver
    container_name: ${APP_NAME}-webserver      
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/usr/share/nginx/html
    ports:
      - "${HTTP_PORT}:80"
    links:
      - avalon-php     
      - avalon-mysql
      
  avalon-php:
    build: ./docker/images/php
    container_name: ${APP_NAME}-php    
    volumes:      
      - ./:/usr/share/nginx/html
      
  avalon-mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql  
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "./docker/.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}      
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME} 




     
        

